apiVersion: v1
data:
  cert.tpl: |-
    {{ with secret "pki/issue/pocnginx-com" "ttl=30s" "common_name=poc.nginx.com" }}
    {{ .Data.certificate }}
    {{ end }}
  key.tpl: |-
    {{ with secret "pki/issue/pocnginx-com" "ttl=30s" "common_name=poc.nginx.com" }}
    {{ .Data.private_key }}
    {{ end }}
  template.hcl: |-
    vault {
      address      = "http://vault:8200"
      ssl {
         enabled = false
       }
      # I'm using the environment variable VAULT_TOKEN instead.
      # token        = "s.xxxxxx"
      # grace        = "1s"
      unwrap_token = false
      renew_token  = false
    }

    log_level = "debug"

    template {
      source      = "/opt/poc/consul-template/cert.tpl"
      destination = "/opt/poc/certs/cert.pem"
      perms       = 0755
      #command     = "nginx reload"
    }

    template {
      source      = "/opt/poc/consul-template/key.tpl"
      destination = "/opt/poc/certs/key.pem"
      perms       = 0755
      #command     = "nginx reload"
    }
kind: ConfigMap
metadata:
  name: consul-template-cfgmap
