apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxct
  name: nginxct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxct
  template:
    metadata:
      labels:
        app: nginxct
    spec:
      serviceAccount: issuer
      volumes:
        - name: consul-template-cfgmap
          configMap:
            name: consul-template-cfgmap
      containers:
      - image: emmerson/nginx-consul-template:1.1
        volumeMounts:
          - mountPath: /opt/poc/consul-template
            name: consul-template-cfgmap
        name: nginx-consul-template
        env:
          - name: ENABLE_CONSUL_TEMPLATE
            value: "true"
          - name: VAULT_TOKEN
            value: "s.uQ4NMKx9j2lbLXkcxIFGeAFU"
        imagePullPolicy: Always
